changelog_type: 'commit_message'
header_prefix: 'Version:'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})'
group_config:
  - title: 'ğŸ’¥ Breaking Changes'
    labels:
      - 'breaking'
      - 'BREAKING CHANGE'

  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'

  - title: 'ğŸ“š Documentation'
    labels:
      - 'documentation'
      - 'docs'

  - title: 'ğŸ”§ Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'

exclude_labels:
  - 'skip-changelog'
  - 'no-changelog'
